# Dataset 1

In [157]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

In [207]:
df=pd.read_excel("Bank_Personal_Loan_Modelling.xlsx","Data")
df.drop(columns=["ID"],inplace=True)
cols=['Age',
 'Experience',
 'Income',
 'ZIP Code',
 'Family',
 'CCAvg',
 'Education',
 'Mortgage',
 'CreditCard',
 'Securities Account',
 'CD Account',
 'Online',
 'Personal Loan']
df=df[cols]
df1=pd.DataFrame(df,copy=True)
df.head()

Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   25           1      49     91107       4    1.6          1         0   
1   45          19      34     90089       3    1.5          1         0   
2   39          15      11     94720       1    1.0          1         0   
3   35           9     100     94112       1    2.7          2         0   
4   35           8      45     91330       4    1.0          2         0   

   CreditCard  Securities Account  CD Account  Online  Personal Loan  
0           0                   1           0       0              0  
1           0                   1           0       0              0  
2           0                   0           0       0              0  
3           0                   0           0       0              0  
4           1                   0           0       0              0

In [208]:
df[df["Personal Loan"]==0].count()

Age                   4520
Experience            4520
Income                4520
ZIP Code              4520
Family                4520
CCAvg                 4520
Education             4520
Mortgage              4520
CreditCard            4520
Securities Account    4520
CD Account            4520
Online                4520
Personal Loan         4520
dtype: int64

In [209]:
df.drop(df[df["Personal Loan"]==0].index[[i for i in range(0,4500)]],inplace=True)

In [210]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 500 entries, 9 to 4999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Age                 500 non-null    int64  
 1   Experience          500 non-null    int64  
 2   Income              500 non-null    int64  
 3   ZIP Code            500 non-null    int64  
 4   Family              500 non-null    int64  
 5   CCAvg               500 non-null    float64
 6   Education           500 non-null    int64  
 7   Mortgage            500 non-null    int64  
 8   CreditCard          500 non-null    int64  
 9   Securities Account  500 non-null    int64  
 10  CD Account          500 non-null    int64  
 11  Online              500 non-null    int64  
 12  Personal Loan       500 non-null    int64  
dtypes: float64(1), int64(12)
memory usage: 54.7 KB


In [211]:
scaler=StandardScaler()
df.iloc[:,0:12]=scaler.fit_transform(df.iloc[:,0:12])

In [212]:

df.head()

Age  Experience    Income  ZIP Code    Family     CCAvg  Education  \
9  -0.939770   -0.920536  1.072807 -0.072576 -1.433982  2.405121   1.020788   
16 -0.596538   -0.491422 -0.332936  1.055088  1.248029  0.414807   1.020788   
18  0.089927    0.109338  1.438300 -0.877888 -0.539978  2.026014   1.020788   
29 -0.596538   -0.577245 -0.642200  0.540914 -1.433982 -0.248631  -0.298060   
38 -0.253305   -0.148130 -0.023673  0.546590  0.354026  0.556972   1.020788   

    Mortgage  CreditCard  Securities Account  CD Account    Online  \
9  -0.626195   -0.654654           -0.369274   -0.623610 -1.229863   
16  0.219639   -0.654654           -0.369274   -0.623610 -1.229863   
18 -0.626195   -0.654654           -0.369274   -0.623610 -1.229863   
29 -0.626195    1.527525           -0.369274    1.603567  0.813099   
38 -0.626195   -0.654654            2.708013    1.603567  0.813099   

    Personal Loan  
9               1  
16              1  
18              1  
29              1  
38              1

In [213]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 500 entries, 9 to 4999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Age                 500 non-null    float64
 1   Experience          500 non-null    float64
 2   Income              500 non-null    float64
 3   ZIP Code            500 non-null    float64
 4   Family              500 non-null    float64
 5   CCAvg               500 non-null    float64
 6   Education           500 non-null    float64
 7   Mortgage            500 non-null    float64
 8   CreditCard          500 non-null    float64
 9   Securities Account  500 non-null    float64
 10  CD Account          500 non-null    float64
 11  Online              500 non-null    float64
 12  Personal Loan       500 non-null    int64  
dtypes: float64(12), int64(1)
memory usage: 54.7 KB


In [214]:
scaler1=MinMaxScaler()
df1.iloc[:,0:12]=scaler1.fit_transform(df1.iloc[:,0:12])

In [215]:
df1.head()
X_norm=df1.drop(columns=["Personal Loan","Income","Education"])
y_norm=df1["Personal Loan"]

In [216]:
X_std=df.drop(columns=["Personal Loan","Income","Education"])
y_std=df["Personal Loan"]


In [217]:
X_n_train, X_n_test, y_n_train, y_n_test = train_test_split(X_norm, y_norm, test_size=0.20, random_state=42)
X_s_train, X_s_test, y_s_train, y_s_test = train_test_split(X_std, y_std, test_size=0.20, random_state=42)

In [218]:
model1=LogisticRegression().fit(X_n_train,y_n_train)
model2=LogisticRegression().fit(X_s_train,y_s_train)
print("Standardized Score (train)- ",model2.score(X_s_train,y_s_train))
print("Normalized Score (train) - ",model1.score(X_n_train,y_n_train))
print("Standardized Score (test)- ",model2.score(X_s_test,y_s_test))
print("Normalized Score (test) - ",model1.score(X_n_test,y_n_test))

Standardized Score (train)-  0.97
Normalized Score (train) -  0.92225
Standardized Score (test)-  0.93
Normalized Score (test) -  0.91


In [219]:
model1=DecisionTreeClassifier().fit(X_n_train,y_n_train)
model2=DecisionTreeClassifier().fit(X_s_train,y_s_train)
print("Standardized Score (train)- ",model2.score(X_s_train,y_s_train))
print("Normalized Score (train) - ",model1.score(X_n_train,y_n_train))
print("Standardized Score (test)- ",model2.score(X_s_test,y_s_test))
print("Normalized Score (test) - ",model1.score(X_n_test,y_n_test))

Standardized Score (train)-  1.0
Normalized Score (train) -  1.0
Standardized Score (test)-  0.92
Normalized Score (test) -  0.911


In [354]:
print(model1.feature_importances_)
print()
print(model2.feature_importances_)

[0.07342284 0.0315693  0.089164   0.19789323 0.40298921 0.06527343
 0.01845264 0.01024658 0.09242616 0.0185626 ]

[0.06531351 0.0417044  0.08843681 0.19204967 0.40714464 0.06527343
 0.01845264 0.01375272 0.09242616 0.01544603]


In [202]:
!git init
!git add .
!git commit -m "dataset 1 epicly fails. pain."
!git push

Reinitialized existing Git repository in C:/Users/RAGHAV VERMA/Documents/JupyterStuff/AI-ML-Labs/week-5-testing/.git/


The file will have its original line endings in your working directory


[master edde705] dataset 1 epicly fails. pain.
 1 file changed, 1169 insertions(+), 1279 deletions(-)


To https://github.com/raghavverma651/AI-ML-Labs.git
   eba3a7d..edde705  master -> master


# Dataset 2

In [203]:
from sklearn.model_selection import GridSearchCV
df=pd.read_csv("census_income_dataset_preprocessed.csv")
#df.drop(columns=['Address'],inplace=True)
df1=pd.DataFrame(df,copy=True)
df.head()

age  workclass  education-num  marital-status  occupation  capital-gains  \
0   39          6             13               4           0           2174   
1   50          5             13               2           3              0   
2   38          3              9               0           5              0   
3   53          3              7               2           5              0   
4   28          3             13               2           9              0   

   capital-loss  hours-per-week  native-country  target  
0             0              40              38       0  
1             0              13              38       0  
2             0              40              38       0  
3             0              40              38       0  
4             0              40               4       0

In [64]:
scaler=StandardScaler()
df.iloc[:,0:9]=scaler.fit_transform(df.iloc[:,0:9])
df.head()

age  workclass  education-num  marital-status  occupation  \
0  0.075615   1.601244       1.125763        0.999672   -1.540417   
1  0.894280   0.991943       1.125763       -0.366000   -0.850884   
2  0.001191  -0.226660      -0.414268       -1.731672   -0.391195   
3  1.117552  -0.226660      -1.184284       -0.366000   -0.391195   
4 -0.743050  -0.226660       1.125763       -0.366000    0.528182   

   capital-gains  capital-loss  hours-per-week  native-country  target  
0       0.608817     -0.245417        0.034964        0.257887       0  
1      -0.213606     -0.245417       -2.256348        0.257887       0  
2      -0.213606     -0.245417        0.034964        0.257887       0  
3      -0.213606     -0.245417        0.034964        0.257887       0  
4      -0.213606     -0.245417        0.034964       -5.277565       0

In [65]:
scaler1=MinMaxScaler()
df1.iloc[:,0:9]=scaler1.fit_transform(df1.iloc[:,0:9])
df1.head()

age  workclass  education-num  marital-status  occupation  \
0  0.301370      0.750       0.800000        0.666667    0.000000   
1  0.452055      0.625       0.800000        0.333333    0.214286   
2  0.287671      0.375       0.533333        0.000000    0.357143   
3  0.493151      0.375       0.400000        0.333333    0.357143   
4  0.150685      0.375       0.800000        0.333333    0.642857   

   capital-gains  capital-loss  hours-per-week  native-country  target  
0       0.063763           0.0        0.402062        0.926829       0  
1       0.000000           0.0        0.123711        0.926829       0  
2       0.000000           0.0        0.402062        0.926829       0  
3       0.000000           0.0        0.402062        0.926829       0  
4       0.000000           0.0        0.402062        0.097561       0

In [66]:
X_norm=df1.iloc[:,0:9]
y_norm=df1["target"]
X_std=df.iloc[:,0:9]
y_std=df["target"]

In [67]:
X_n_train, X_n_test, y_n_train, y_n_test = train_test_split(X_norm, y_norm, test_size=0.30, random_state=42)
X_s_train, X_s_test, y_s_train, y_s_test = train_test_split(X_std, y_std, test_size=0.30, random_state=42)

In [68]:
model1=LogisticRegression().fit(X_n_train,y_n_train)
model2=LogisticRegression().fit(X_s_train,y_s_train)
print("Standardized Score (train)- ",model2.score(X_s_train,y_s_train))
print("Normalized Score (train) - ",model1.score(X_n_train,y_n_train))
print("Standardized Score (test)- ",model2.score(X_s_test,y_s_test))
print("Normalized Score (test) - ",model1.score(X_n_test,y_n_test))


Standardized Score (train)-  0.8085714285714286
Normalized Score (train) -  0.7942857142857143
Standardized Score (test)-  0.82
Normalized Score (test) -  0.7866666666666666


In [69]:
model1=DecisionTreeClassifier().fit(X_n_train,y_n_train)
model2=DecisionTreeClassifier().fit(X_s_train,y_s_train)
print("Standardized Score (train)- ",model2.score(X_s_train,y_s_train))
print("Normalized Score (train) - ",model1.score(X_n_train,y_n_train))
print("Standardized Score (test)- ",model2.score(X_s_test,y_s_test))
print("Normalized Score (test) - ",model1.score(X_n_test,y_n_test))

Standardized Score (train)-  0.9914285714285714
Normalized Score (train) -  0.9914285714285714
Standardized Score (test)-  0.7666666666666667
Normalized Score (test) -  0.7866666666666666


# Dataset 3

In [223]:
df=pd.read_csv("data.csv")
df.drop(columns=["Unnamed: 32",'id'],inplace=True)
df1=pd.DataFrame(df,copy=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [231]:
df.drop(df[df["diagnosis"]=="B"].index[[i for i in range(0,326)]],inplace=True)

In [232]:
scaler=StandardScaler()
df.iloc[:,1:]=scaler.fit_transform(df.iloc[:,1:])
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M     0.352729     -2.922764        0.507718   0.239793   
1         M     1.057621     -1.020073        0.909519   1.064195   
2         M     0.817193     -0.124083        0.794150   0.752190   
3         M    -1.442289     -0.348080       -1.291235  -1.319975   
4         M     0.981121     -1.903189        0.997040   0.990633   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0         1.291948          2.520532        1.899423             1.719287   
1        -1.248808         -1.042639       -0.717204            -0.236386   
2         0.627698          0.412645        0.638974             1.231195   
3         3.111088          2.633358        1.178991             0.654128   
4        -0.074293         -0.072688        0.646338             0.631248   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0       1.861017  ...      1.075541      -2.189633         1.481674   
1      -0.313152  ...      0.996804      -1.074951         0.729302   
2       0.607378  ...      0.710121      -0.686279         0.545584   
3       2.498583  ...     -1.038239      -0.508444        -1.018357   
4      -0.323897  ...      0.502176      -2.310635         0.536835   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0    1.117378          0.881802           1.807512         1.489919   
1    1.018815         -0.827762          -0.932082        -0.843625   
2    0.632384          0.089348           0.428564         0.192403   
3   -1.153175          3.000948           2.955396         1.365874   
4    0.422742         -0.222292          -0.826845        -0.057673   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0              1.632776        1.956970                 1.382792  
1              0.314269       -0.539192                -0.047282  
2              1.260804        0.624605                -0.116201  
3              1.501589        4.703962                 3.972049  
4             -0.075969       -1.059731                -0.633095  

[5 rows x 31 columns]

In [233]:
scaler1=MinMaxScaler()
df1.iloc[:,1:]=scaler1.fit_transform(df1.iloc[:,1:])
df1.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M     0.521037      0.022658        0.545989   0.363733   
1         M     0.643144      0.272574        0.615783   0.501591   
2         M     0.601496      0.390260        0.595743   0.449417   
3         M     0.210090      0.360839        0.233501   0.102906   
4         M     0.629893      0.156578        0.630986   0.489290   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0         0.593753          0.792037        0.703140             0.731113   
1         0.289880          0.181768        0.203608             0.348757   
2         0.514309          0.431017        0.462512             0.635686   
3         0.811321          0.811361        0.565604             0.522863   
4         0.430351          0.347893        0.463918             0.518390   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0       0.686364  ...      0.620776       0.141525         0.668310   
1       0.379798  ...      0.606901       0.303571         0.539818   
2       0.509596  ...      0.556386       0.360075         0.508442   
3       0.776263  ...      0.248310       0.385928         0.241347   
4       0.378283  ...      0.519744       0.123934         0.506948   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0    0.450698          0.601136           0.619292         0.568610   
1    0.435214          0.347553           0.154563         0.192971   
2    0.374508          0.483590           0.385375         0.359744   
3    0.094008          0.915472           0.814012         0.548642   
4    0.341575          0.437364           0.172415         0.319489   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0              0.912027        0.598462                 0.418864  
1              0.639175        0.233590                 0.222878  
2              0.835052        0.403706                 0.213433  
3              0.884880        1.000000                 0.773711  
4              0.558419        0.157500                 0.142595  

[5 rows x 31 columns]

In [234]:
X_norm=df1.iloc[:,1:]
y_norm=df1["diagnosis"]
X_std=df.iloc[:,1:]
y_std=df["diagnosis"]

In [235]:
X_n_train, X_n_test, y_n_train, y_n_test = train_test_split(X_norm, y_norm, test_size=0.30, random_state=42)
X_s_train, X_s_test, y_s_train, y_s_test = train_test_split(X_std, y_std, test_size=0.30, random_state=42)

In [236]:
model1=LogisticRegression().fit(X_n_train,y_n_train)
model2=LogisticRegression().fit(X_s_train,y_s_train)
print("Standardized Score (train)- ",model2.score(X_s_train,y_s_train))
print("Normalized Score (train) - ",model1.score(X_n_train,y_n_train))
print("Standardized Score (test)- ",model2.score(X_s_test,y_s_test))
print("Normalized Score (test) - ",model1.score(X_n_test,y_n_test))

Standardized Score (train)-  0.9882352941176471
Normalized Score (train) -  0.9673366834170855
Standardized Score (test)-  0.9452054794520548
Normalized Score (test) -  0.9766081871345029


In [237]:
model1=DecisionTreeClassifier().fit(X_n_train,y_n_train)
model2=DecisionTreeClassifier().fit(X_s_train,y_s_train)
print("Standardized Score (train)- ",model2.score(X_s_train,y_s_train))
print("Normalized Score (train) - ",model1.score(X_n_train,y_n_train))
print("Standardized Score (test)- ",model2.score(X_s_test,y_s_test))
print("Normalized Score (test) - ",model1.score(X_n_test,y_n_test))

Standardized Score (train)-  1.0
Normalized Score (train) -  1.0
Standardized Score (test)-  0.9315068493150684
Normalized Score (test) -  0.9415204678362573


# Dataset 4

In [238]:
df=pd.read_csv("StudentsPerformance.csv")
#df.drop(columns=["Unnamed: 32",'id'],inplace=True)
df=df.iloc[0:500,:]
df1=pd.DataFrame(df,copy=True)
df.head()

gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

In [92]:
df["gender"]=df["gender"].apply(lambda x : 1 if x=="male" else 0)
df.head()

gender race/ethnicity parental level of education         lunch  \
0       0        group B           bachelor's degree      standard   
1       0        group C                some college      standard   
2       0        group B             master's degree      standard   
3       1        group A          associate's degree  free/reduced   
4       1        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

In [93]:
ohe=pd.get_dummies(df.iloc[:,1:4])

In [94]:
ohe

race/ethnicity_group A  race/ethnicity_group B  race/ethnicity_group C  \
0                         0                       1                       0   
1                         0                       0                       1   
2                         0                       1                       0   
3                         1                       0                       0   
4                         0                       0                       1   
..                      ...                     ...                     ...   
495                       0                       0                       0   
496                       0                       0                       1   
497                       0                       0                       0   
498                       0                       1                       0   
499                       0                       0                       0   

     race/ethnicity_group D  race/ethnicity_group E  \
0                         0                       0   
1                         0                       0   
2                         0                       0   
3                         0                       0   
4                         0                       0   
..                      ...                     ...   
495                       1                       0   
496                       0                       0   
497                       1                       0   
498                       0                       0   
499                       0                       1   

     parental level of education_associate's degree  \
0                                                 0   
1                                                 0   
2                                                 0   
3                                                 1   
4                                                 0   
..                                              ...   
495                                               0   
496                                               0   
497                                               0   
498                                               0   
499                                               0   

     parental level of education_bachelor's degree  \
0                                                1   
1                                                0   
2                                                0   
3                                                0   
4                                                0   
..                                             ...   
495                                              0   
496                                              0   
497                                              0   
498                                              0   
499                                              0   

     parental level of education_high school  \
0                                          0   
1                                          0   
2                                          0   
3                                          0   
4                                          0   
..                                       ...   
495                                        1   
496                                        0   
497                                        0   
498                                        0   
499                                        0   

     parental level of education_master's degree  \
0                                              0   
1                                              0   
2                                              1   
3                                              0   
4                                              0   
..                                           ...   
495                                            0   
496                                            0   
497                                     

In [95]:
df = pd.concat([df.drop(columns=['race/ethnicity',
                                 'parental level of education','lunch']), ohe], axis=1)

In [96]:
df

gender test preparation course  math score  reading score  writing score  \
0         0                    none          72             72             74   
1         0               completed          69             90             88   
2         0                    none          90             95             93   
3         1                    none          47             57             44   
4         1                    none          76             78             75   
..      ...                     ...         ...            ...            ...   
495       1               completed          68             64             66   
496       0                    none          54             48             52   
497       0               completed          59             78             76   
498       0                    none          66             69             68   
499       1                    none          76             71             72   

     race/ethnicity_group A  race/ethnicity_group B  race/ethnicity_group C  \
0                         0                       1                       0   
1                         0                       0                       1   
2                         0                       1                       0   
3                         1                       0                       0   
4                         0                       0                       1   
..                      ...                     ...                     ...   
495                       0                       0                       0   
496                       0                       0                       1   
497                       0                       0                       0   
498                       0                       1                       0   
499                       0                       0                       0   

     race/ethnicity_group D  race/ethnicity_group E  \
0                         0                       0   
1                         0                       0   
2                         0                       0   
3                         0                       0   
4                         0                       0   
..                      ...                     ...   
495                       1                       0   
496                       0                       0   
497                       1                       0   
498                       0                       0   
499                       0                       1   

     parental level of education_associate's degree  \
0                                                 0   
1                                                 0   
2                                                 0   
3                                                 1   
4                                                 0   
..                                              ...   
495                                               0   
496                                               0   
497                                               0   
498                                               0   
499                                               0   

     parental level of education_bachelor's degree  \
0                                                1   
1                                                0   
2                                                0   
3                                                0   
4                                                0   
..                                             ...   
495                                              0   
496                                              0   
497                                              0   
498                                              0   
499                                              0   

     parental level of education_high school  \
0                                          0   
1               

In [97]:
df["test preparation course"]=df["test preparation course"].apply(lambda x : 1 if x=="completed" else 0)

In [98]:
df

gender  test preparation course  math score  reading score  \
0         0                        0          72             72   
1         0                        1          69             90   
2         0                        0          90             95   
3         1                        0          47             57   
4         1                        0          76             78   
..      ...                      ...         ...            ...   
495       1                        1          68             64   
496       0                        0          54             48   
497       0                        1          59             78   
498       0                        0          66             69   
499       1                        0          76             71   

     writing score  race/ethnicity_group A  race/ethnicity_group B  \
0               74                       0                       1   
1               88                       0                       0   
2               93                       0                       1   
3               44                       1                       0   
4               75                       0                       0   
..             ...                     ...                     ...   
495             66                       0                       0   
496             52                       0                       0   
497             76                       0                       0   
498             68                       0                       1   
499             72                       0                       0   

     race/ethnicity_group C  race/ethnicity_group D  race/ethnicity_group E  \
0                         0                       0                       0   
1                         1                       0                       0   
2                         0                       0                       0   
3                         0                       0                       0   
4                         1                       0                       0   
..                      ...                     ...                     ...   
495                       0                       1                       0   
496                       1                       0                       0   
497                       0                       1                       0   
498                       0                       0                       0   
499                       0                       0                       1   

     parental level of education_associate's degree  \
0                                                 0   
1                                                 0   
2                                                 0   
3                                                 1   
4                                                 0   
..                                              ...   
495                                               0   
496                                               0   
497                                               0   
498                                               0   
499                                               0   

     parental level of education_bachelor's degree  \
0                                                1   
1                                                0   
2                                                0   
3                                                0   
4                                                0   
..                                             ...   
495                                              0   
496                                              0   
497                                              0   
498                                              0   
499                                              0   

     parental level of education_high school  \
0                                          0   
1   

In [99]:
df1=pd.DataFrame(df,copy=True)

In [100]:
scaler=StandardScaler()
df.iloc[:,2:5]=scaler.fit_transform(df.iloc[:,2:5])
df.head()

gender  test preparation course  math score  reading score  writing score  \
0       0                        0    0.418361       0.238374       0.440397   
1       0                        1    0.218698       1.460108       1.358711   
2       0                        0    1.616338       1.799479       1.686680   
3       1                        0   -1.245498      -0.779738      -1.527418   
4       1                        0    0.684578       0.645619       0.505991   

   race/ethnicity_group A  race/ethnicity_group B  race/ethnicity_group C  \
0                       0                       1                       0   
1                       0                       0                       1   
2                       0                       1                       0   
3                       1                       0                       0   
4                       0                       0                       1   

   race/ethnicity_group D  race/ethnicity_group E  \
0                       0                       0   
1                       0                       0   
2                       0                       0   
3                       0                       0   
4                       0                       0   

   parental level of education_associate's degree  \
0                                               0   
1                                               0   
2                                               0   
3                                               1   
4                                               0   

   parental level of education_bachelor's degree  \
0                                              1   
1                                              0   
2                                              0   
3                                              0   
4                                              0   

   parental level of education_high school  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   

   parental level of education_master's degree  \
0                                            0   
1                                            0   
2                                            1   
3                                            0   
4                                            0   

   parental level of education_some college  \
0                                         0   
1                                         1   
2                                         0   
3                                         0   
4                                         1   

   parental level of education_some high school  lunch_free/reduced  \
0                                             0                   0   
1                                             0                   0   
2                                             0                   0   
3                                             0                   1   
4                                             0                   0   

   lunch_standard  
0               1  
1               1  
2               1  
3               0  
4               1

In [101]:
scaler1=MinMaxScaler()
df1.iloc[:,2:5]=scaler1.fit_transform(df1.iloc[:,2:5])
df1.head()

gender  test preparation course  math score  reading score  writing score  \
0       0                        0        0.72       0.662651       0.711111   
1       0                        1        0.69       0.879518       0.866667   
2       0                        0        0.90       0.939759       0.922222   
3       1                        0        0.47       0.481928       0.377778   
4       1                        0        0.76       0.734940       0.722222   

   race/ethnicity_group A  race/ethnicity_group B  race/ethnicity_group C  \
0                       0                       1                       0   
1                       0                       0                       1   
2                       0                       1                       0   
3                       1                       0                       0   
4                       0                       0                       1   

   race/ethnicity_group D  race/ethnicity_group E  \
0                       0                       0   
1                       0                       0   
2                       0                       0   
3                       0                       0   
4                       0                       0   

   parental level of education_associate's degree  \
0                                               0   
1                                               0   
2                                               0   
3                                               1   
4                                               0   

   parental level of education_bachelor's degree  \
0                                              1   
1                                              0   
2                                              0   
3                                              0   
4                                              0   

   parental level of education_high school  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   

   parental level of education_master's degree  \
0                                            0   
1                                            0   
2                                            1   
3                                            0   
4                                            0   

   parental level of education_some college  \
0                                         0   
1                                         1   
2                                         0   
3                                         0   
4                                         1   

   parental level of education_some high school  lunch_free/reduced  \
0                                             0                   0   
1                                             0                   0   
2                                             0                   0   
3                                             0                   1   
4                                             0                   0   

   lunch_standard  
0               1  
1               1  
2               1  
3               0  
4               1

In [102]:
X_norm=df1.iloc[:,2:]
X_norm.insert(0,"gender",df1["gender"])
y_norm=df1["test preparation course"]
X_std=df.iloc[:,2:]
X_std.insert(0,"gender",df["gender"])
y_std=df["test preparation course"]

In [103]:
X_n_train, X_n_test, y_n_train, y_n_test = train_test_split(X_norm, y_norm, test_size=0.4)
X_s_train, X_s_test, y_s_train, y_s_test = train_test_split(X_std, y_std, test_size=0.4)

In [104]:
model1=LogisticRegression().fit(X_n_train,y_n_train)
model2=LogisticRegression().fit(X_s_train,y_s_train)
print("Standardized Score (train)- ",model2.score(X_s_train,y_s_train))
print("Normalized Score (train) - ",model1.score(X_n_train,y_n_train))
print("Standardized Score (test)- ",model2.score(X_s_test,y_s_test))
print("Normalized Score (test) - ",model1.score(X_n_test,y_n_test))

Standardized Score (train)-  0.7866666666666666
Normalized Score (train) -  0.7033333333333334
Standardized Score (test)-  0.71
Normalized Score (test) -  0.685


In [105]:
model1=DecisionTreeClassifier().fit(X_n_train,y_n_train)
model2=DecisionTreeClassifier().fit(X_s_train,y_s_train)
print("Standardized Score (train)- ",model2.score(X_s_train,y_s_train))
print("Normalized Score (train) - ",model1.score(X_n_train,y_n_train))
print("Standardized Score (test)- ",model2.score(X_s_test,y_s_test))
print("Normalized Score (test) - ",model1.score(X_n_test,y_n_test))

Standardized Score (train)-  1.0
Normalized Score (train) -  1.0
Standardized Score (test)-  0.65
Normalized Score (test) -  0.625


# Dataset 5

In [246]:
df=pd.read_csv("mushrooms.csv")
df.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [247]:
df.drop(df[df["class"]=='p'].index[[i for i in range(0,3716)]],inplace=True)

In [248]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4408 entries, 1 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     4408 non-null   object
 1   cap-shape                 4408 non-null   object
 2   cap-surface               4408 non-null   object
 3   cap-color                 4408 non-null   object
 4   bruises                   4408 non-null   object
 5   odor                      4408 non-null   object
 6   gill-attachment           4408 non-null   object
 7   gill-spacing              4408 non-null   object
 8   gill-size                 4408 non-null   object
 9   gill-color                4408 non-null   object
 10  stalk-shape               4408 non-null   object
 11  stalk-root                4408 non-null   object
 12  stalk-surface-above-ring  4408 non-null   object
 13  stalk-surface-below-ring  4408 non-null   object
 14  stalk-color-above-ring  

In [249]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [250]:
for i in df.columns:
    df[i]=le.fit_transform(df[i])
df.head()

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
1      0          4            1          9        1     0                1   
2      0          0            1          8        1     2                1   
4      0          4            1          3        0     4                1   
5      0          4            2          9        1     0                1   
6      0          0            1          8        1     0                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
4             1          0           4  ...                         2   
5             0          0           5  ...                         2   
6             0          0           2  ...                         2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
1                       6                       6          0           2   
2                       6                       6          0           2   
4                       6                       6          0           2   
5                       6                       6          0           2   
6                       6                       6          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
1            1          3                  3           2        1  
2            1          3                  3           2        3  
4            1          0                  3           0        1  
5            1          3                  2           2        1  
6            1          3                  2           2        3  

[5 rows x 23 columns]

In [251]:
for i in df.columns:
    print(df[i].unique())

[0 1]
[4 0 3 1 2]
[1 2 0]
[9 8 3 4 2 0 7 1 5 6]
[1 0]
[0 2 4 1 5 6 3]
[1 0]
[0 1]
[0 1]
[ 4  5  2  9  7  3  8  1 10  6  0]
[0 1]
[2 3 1 4 0]
[2 0 1 3]
[2 0 3 1]
[6 2 5 1 4 3 7 0]
[6 5 2 3 1 4 7 0]
[0]
[2 0 1 3]
[1 2 0]
[3 0 1 2]
[3 2 5 6 1 4 7 0]
[2 0 3 5 4 1]
[1 3 5 0 4 6 2]


In [252]:
from sklearn import preprocessing
df.iloc[:,1:]=preprocessing.scale(df.iloc[:,1:])
df.head()

class  cap-shape  cap-surface  cap-color   bruises      odor  \
1      0   1.065420    -0.013111   1.860619  0.775722 -2.622099   
2      0  -1.517133    -0.013111   1.446291  0.775722 -1.097772   
4      0   1.065420    -0.013111  -0.625345 -1.289122  0.426556   
5      0   1.065420     1.166386   1.860619  0.775722 -2.622099   
6      0  -1.517133    -0.013111   1.446291  0.775722 -2.622099   

   gill-attachment  gill-spacing  gill-size  gill-color  ...  \
1         0.216292     -0.611959  -0.349571   -0.773346  ...   
2         0.216292     -0.611959  -0.349571   -0.388463  ...   
4         0.216292      1.634098  -0.349571   -0.773346  ...   
5         0.216292     -0.611959  -0.349571   -0.388463  ...   
6         0.216292     -0.611959  -0.349571   -1.543113  ...   

   stalk-surface-below-ring  stalk-color-above-ring  stalk-color-below-ring  \
1                  0.306289                0.592694                0.609224   
2                  0.306289                0.592694                0.609224   
4                  0.306289                0.592694                0.609224   
5                  0.306289                0.592694                0.609224   
6                  0.306289                0.592694                0.609224   

   veil-type  veil-color  ring-number  ring-type  spore-print-color  \
1        0.0    0.201045    -0.359495   0.628172          -0.116143   
2        0.0    0.201045    -0.359495   0.628172          -0.116143   
4        0.0    0.201045    -0.359495  -1.614525          -0.116143   
5        0.0    0.201045    -0.359495   0.628172          -0.775882   
6        0.0    0.201045    -0.359495   0.628172          -0.775882   

   population   habitat  
1   -0.858421 -0.113459  
2   -0.858421  1.136856  
4   -2.169325 -0.113459  
5   -0.858421 -0.113459  
6   -0.858421  1.136856  

[5 rows x 23 columns]

In [253]:
X=df.drop(columns=['class'])
y=df['class']

In [254]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=42)

In [255]:
model=LogisticRegression().fit(X_train,y_train)
print("Score (train)- ",model.score(X_train,y_train))
print("Score (test) - ",model.score(X_test,y_test))

Score (train)-  1.0
Score (test) -  1.0


In [256]:
model1=DecisionTreeClassifier().fit(X_train,y_train)
model2=DecisionTreeClassifier().fit(X_train,y_train)
print("Score (train)- ",model.score(X_train,y_train))
print("Score (test) - ",model.score(X_test,y_test))

Score (train)-  1.0
Score (test) -  1.0


# Mushroom Final Dataset Operations

In [273]:
df=pd.read_csv("mushrooms_finalized.csv")
df.drop(columns="Unnamed: 0",inplace=True)
df.head()

class cap-shape cap-surface cap-color odor gill-attachment gill-spacing  \
0     p         x           s         n    p               f            c   
1     e         x           s         y    a               f            c   
2     e         b           s         w    l               f            c   
3     p         x           y         w    p               f            c   
4     e         x           s         g    n               f            w   

  gill-color stalk-shape stalk-root stalk-surface-above-ring  \
0          k           e          e                        s   
1          k           e          c                        s   
2          n           e          c                        s   
3          n           e          e                        s   
4          k           t          e                        s   

  stalk-surface-below-ring stalk-color-below-ring veil-type veil-color  \
0                        s                      w         p          w   
1                        s                      w         p          w   
2                        s                      w         p          w   
3                        s                      w         p          w   
4                        s                      w         p          w   

  ring-number ring-type spore-print-color population  
0           o         p                 k          s  
1           o         p                 n          n  
2           o         p                 n          n  
3           o         p                 k          s  
4           o         e                 n          a

In [274]:
df.drop(df[df["class"]=='p'].index[[i for i in range(0,3716)]],inplace=True)

In [275]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['class']=le.fit_transform(df['class'])


In [276]:
df.head()

class cap-shape cap-surface cap-color odor gill-attachment gill-spacing  \
1      0         x           s         y    a               f            c   
2      0         b           s         w    l               f            c   
4      0         x           s         g    n               f            w   
5      0         x           y         y    a               f            c   
6      0         b           s         w    a               f            c   

  gill-color stalk-shape stalk-root stalk-surface-above-ring  \
1          k           e          c                        s   
2          n           e          c                        s   
4          k           t          e                        s   
5          n           e          c                        s   
6          g           e          c                        s   

  stalk-surface-below-ring stalk-color-below-ring veil-type veil-color  \
1                        s                      w         p          w   
2                        s                      w         p          w   
4                        s                      w         p          w   
5                        s                      w         p          w   
6                        s                      w         p          w   

  ring-number ring-type spore-print-color population  
1           o         p                 n          n  
2           o         p                 n          n  
4           o         e                 n          a  
5           o         p                 k          n  
6           o         p                 k          n

In [265]:
X=df.drop(columns=['class'])
y=df['class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=42)
model=LogisticRegression().fit(X_train,y_train)
print(model.score(X_test,y_test))
print(model.score(X_train,y_train))

1.0
1.0


In [279]:

X=pd.get_dummies(df.drop(columns=['class','bruises','gill-size','stalk-color-above-ring','habitat']))
y=df['class']

KeyError: "['bruises' 'gill-size' 'stalk-color-above-ring' 'habitat'] not found in axis"

In [266]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=42)

In [267]:
from sklearn.metrics import accuracy_score
model=LogisticRegression().fit(X_train,y_train)
print("Score (train)- ",accuracy_score(y_train,model.predict(X_train)))
print("Score (test) - ",accuracy_score(y_test,model.predict(X_test)))

Score (train)-  1.0
Score (test) -  1.0


In [268]:
model=DecisionTreeClassifier().fit(X_train,y_train)
print("Score (train)- ",accuracy_score(y_train,model.predict(X_train)))
print("Score (test) - ",accuracy_score(y_test,model.predict(X_test)))

Score (train)-  1.0
Score (test) -  1.0


In [155]:
df2=df.drop(columns=['bruises','gill-size','stalk-color-above-ring','habitat'])
df2.info()

KeyError: "['bruises' 'gill-size' 'stalk-color-above-ring' 'habitat'] not found in axis"

In [156]:
df2.to_csv("mushrooms_finalized.csv")

NameError: name 'df2' is not defined

In [184]:
pd.read_csv("mushrooms_finalized.csv")

Unnamed: 0 class cap-shape cap-surface cap-color odor gill-attachment  \
0              0     p         x           s         n    p               f   
1              1     e         x           s         y    a               f   
2              2     e         b           s         w    l               f   
3              3     p         x           y         w    p               f   
4              4     e         x           s         g    n               f   
...          ...   ...       ...         ...       ...  ...             ...   
8119        8119     e         k           s         n    n               a   
8120        8120     e         x           s         n    n               a   
8121        8121     e         f           s         n    n               a   
8122        8122     p         k           y         n    y               f   
8123        8123     e         x           s         n    n               a   

     gill-spacing gill-color stalk-shape stalk-root stalk-surface-above-ring  \
0               c          k           e          e                        s   
1               c          k           e          c                        s   
2               c          n           e          c                        s   
3               c          n           e          e                        s   
4               w          k           t          e                        s   
...           ...        ...         ...        ...                      ...   
8119            c          y           e          ?                        s   
8120            c          y           e          ?                        s   
8121            c          n           e          ?                        s   
8122            c          b           t          ?                        s   
8123            c          y           e          ?                        s   

     stalk-surface-below-ring stalk-color-below-ring veil-type veil-color  \
0                           s                      w         p          w   
1                           s                      w         p          w   
2                           s                      w         p          w   
3                           s                      w         p          w   
4                           s                      w         p          w   
...                       ...                    ...       ...        ...   
8119                        s                      o         p          o   
8120                        s                      o         p          n   
8121                        s                      o         p          o   
8122                        k                      w         p          w   
8123                        s                      o         p          o   

     ring-number ring-type spore-print-color population  
0              o         p                 k          s  
1              o         p                 n          n  
2              o         p                 n          n  
3              o         p                 k          s  
4              o         e                 n          a  
...          ...       ...               ...        ...  
8119           o         p                 b          c  
8120           o         p                 b          v  
8121           o         p                 b          c  
8122           o         e                 w          v  
8123           o         p                 o          c  

[8124 rows x 20 columns]