# Dataset 1

In [17]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

In [22]:
df=pd.read_excel("Bank_Personal_Loan_Modelling.xlsx","Data")
df.drop(columns=["ID"],inplace=True)
cols=['Age',
 'Experience',
 'Income',
 'ZIP Code',
 'Family',
 'CCAvg',
 'Education',
 'Mortgage',
 'CreditCard',
 'Securities Account',
 'CD Account',
 'Online',
 'Personal Loan']
df=df[cols]
df1=pd.DataFrame(df,copy=True)
df.head()

Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   25           1      49     91107       4    1.6          1         0   
1   45          19      34     90089       3    1.5          1         0   
2   39          15      11     94720       1    1.0          1         0   
3   35           9     100     94112       1    2.7          2         0   
4   35           8      45     91330       4    1.0          2         0   

   CreditCard  Securities Account  CD Account  Online  Personal Loan  
0           0                   1           0       0              0  
1           0                   1           0       0              0  
2           0                   0           0       0              0  
3           0                   0           0       0              0  
4           1                   0           0       0              0

In [23]:
scaler=StandardScaler()
df.iloc[:,0:12]=scaler.fit_transform(df.iloc[:,0:12])

In [25]:
df=df.iloc[0:500,:]
df.head()

Age  Experience    Income  ZIP Code    Family     CCAvg  Education  \
0 -1.774417   -1.666078 -0.538229 -0.964114  1.397414 -0.193371  -1.049078   
1 -0.029524   -0.096330 -0.864109 -1.443932  0.525991 -0.250595  -1.049078   
2 -0.552992   -0.445163 -1.363793  0.738814 -1.216855 -0.536720  -1.049078   
3 -0.901970   -0.968413  0.569765  0.452243 -1.216855  0.436103   0.141703   
4 -0.901970   -1.055621 -0.625130 -0.859007  1.397414 -0.536720   0.141703   

   Mortgage  CreditCard  Securities Account  CD Account    Online  \
0 -0.555524   -0.645314            2.928915    -0.25354 -1.216618   
1 -0.555524   -0.645314            2.928915    -0.25354 -1.216618   
2 -0.555524   -0.645314           -0.341423    -0.25354 -1.216618   
3 -0.555524   -0.645314           -0.341423    -0.25354 -1.216618   
4 -0.555524    1.549632           -0.341423    -0.25354 -1.216618   

   Personal Loan  
0              0  
1              0  
2              0  
3              0  
4              0

In [12]:
df.info()

AttributeError: 'Series' object has no attribute 'info'

In [13]:
scaler1=MinMaxScaler()
df1.iloc[:,0:12]=scaler1.fit_transform(df1.iloc[:,0:12])

In [15]:
df1.head()
X_norm=df1.drop(columns=["Personal Loan","Income","Education"])
y_norm=df1["Personal Loan"]

Age  Experience    Income  ZIP Code    Family  CCAvg  Education  \
0  0.045455    0.086957  0.189815  0.936527  1.000000   0.16        0.0   
1  0.500000    0.478261  0.120370  0.924872  0.666667   0.15        0.0   
2  0.363636    0.391304  0.013889  0.977892  0.000000   0.10        0.0   
3  0.272727    0.260870  0.425926  0.970931  0.000000   0.27        0.5   
4  0.272727    0.239130  0.171296  0.939080  1.000000   0.10        0.5   

   Mortgage  CreditCard  Securities Account  CD Account  Online  Personal Loan  
0       0.0         0.0                 1.0         0.0     0.0              0  
1       0.0         0.0                 1.0         0.0     0.0              0  
2       0.0         0.0                 0.0         0.0     0.0              0  
3       0.0         0.0                 0.0         0.0     0.0              0  
4       0.0         1.0                 0.0         0.0     0.0              0

In [348]:
X_std=df.drop(columns=["Personal Loan","Income","Education"])
y_std=df["Personal Loan"]


In [350]:
X_n_train, X_n_test, y_n_train, y_n_test = train_test_split(X_norm, y_norm, test_size=0.20, random_state=42)
X_s_train, X_s_test, y_s_train, y_s_test = train_test_split(X_std, y_std, test_size=0.20, random_state=42)

In [351]:
model1=LogisticRegression().fit(X_n_train,y_n_train)
model2=LogisticRegression().fit(X_s_train,y_s_train)
print("Standardized Score (train)- ",model2.score(X_s_train,y_s_train))
print("Normalized Score (train) - ",model1.score(X_n_train,y_n_train))
print("Standardized Score (test)- ",model2.score(X_s_test,y_s_test))
print("Normalized Score (test) - ",model1.score(X_n_test,y_n_test))

Standardized Score (train)-  0.92175
Normalized Score (train) -  0.92225
Standardized Score (test)-  0.912
Normalized Score (test) -  0.91


In [353]:
model1=DecisionTreeClassifier(max_depth=9).fit(X_n_train,y_n_train)
model2=DecisionTreeClassifier(max_depth=9).fit(X_s_train,y_s_train)
print("Standardized Score (train)- ",model2.score(X_s_train,y_s_train))
print("Normalized Score (train) - ",model1.score(X_n_train,y_n_train))
print("Standardized Score (test)- ",model2.score(X_s_test,y_s_test))
print("Normalized Score (test) - ",model1.score(X_n_test,y_n_test))

Standardized Score (train)-  0.96275
Normalized Score (train) -  0.96275
Standardized Score (test)-  0.935
Normalized Score (test) -  0.935


In [354]:
print(model1.feature_importances_)
print()
print(model2.feature_importances_)

[0.07342284 0.0315693  0.089164   0.19789323 0.40298921 0.06527343
 0.01845264 0.01024658 0.09242616 0.0185626 ]

[0.06531351 0.0417044  0.08843681 0.19204967 0.40714464 0.06527343
 0.01845264 0.01375272 0.09242616 0.01544603]


In [402]:
!git init
!git add .
!git commit -m "dataset 2 ready"
!git push

Reinitialized existing Git repository in C:/Users/RAGHAV VERMA/Documents/JupyterStuff/AI-ML-Labs/week-5-testing/.git/


The file will have its original line endings in your working directory
The file will have its original line endings in your working directory


[master c9e55b2] dataset 2 ready
 2 files changed, 1112 insertions(+), 371 deletions(-)


To https://github.com/raghavverma651/AI-ML-Labs.git
   20d0482..c9e55b2  master -> master


# Dataset 2

In [371]:
from sklearn.model_selection import GridSearchCV
df=pd.read_csv("census_income_dataset_preprocessed.csv")
#df.drop(columns=['Address'],inplace=True)
df1=pd.DataFrame(df,copy=True)
df.head()

age  workclass  education-num  marital-status  occupation  capital-gains  \
0   39          6             13               4           0           2174   
1   50          5             13               2           3              0   
2   38          3              9               0           5              0   
3   53          3              7               2           5              0   
4   28          3             13               2           9              0   

   capital-loss  hours-per-week  native-country  target  
0             0              40              38       0  
1             0              13              38       0  
2             0              40              38       0  
3             0              40              38       0  
4             0              40               4       0

In [372]:
scaler=StandardScaler()
df.iloc[:,0:9]=scaler.fit_transform(df.iloc[:,0:9])
df.head()

age  workclass  education-num  marital-status  occupation  \
0  0.030671   1.658412       1.134739        0.921634   -1.483582   
1  0.837109   1.026306       1.134739       -0.406212   -0.790510   
2 -0.042642  -0.237906      -0.420060       -1.734058   -0.328461   
3  1.057047  -0.237906      -1.197459       -0.406212   -0.328461   
4 -0.775768  -0.237906       1.134739       -0.406212    0.595635   

   capital-gains  capital-loss  hours-per-week  native-country  target  
0       0.148453      -0.21666       -0.035429        0.251378       0  
1      -0.145920      -0.21666       -2.222153        0.251378       0  
2      -0.145920      -0.21666       -0.035429        0.251378       0  
3      -0.145920      -0.21666       -0.035429        0.251378       0  
4      -0.145920      -0.21666       -0.035429       -5.337971       0

In [373]:
scaler1=MinMaxScaler()
df1.iloc[:,0:9]=scaler1.fit_transform(df1.iloc[:,0:9])
df1.head()

age  workclass  education-num  marital-status  occupation  \
0  0.301370      0.750       0.800000        0.666667    0.000000   
1  0.452055      0.625       0.800000        0.333333    0.214286   
2  0.287671      0.375       0.533333        0.000000    0.357143   
3  0.493151      0.375       0.400000        0.333333    0.357143   
4  0.150685      0.375       0.800000        0.333333    0.642857   

   capital-gains  capital-loss  hours-per-week  native-country  target  
0        0.02174           0.0        0.397959        0.926829       0  
1        0.00000           0.0        0.122449        0.926829       0  
2        0.00000           0.0        0.397959        0.926829       0  
3        0.00000           0.0        0.397959        0.926829       0  
4        0.00000           0.0        0.397959        0.097561       0

In [374]:
X_norm=df1.iloc[:,0:9]
y_norm=df1["target"]
X_std=df.iloc[:,0:9]
y_std=df["target"]

In [375]:
X_n_train, X_n_test, y_n_train, y_n_test = train_test_split(X_norm, y_norm, test_size=0.15, random_state=42)
X_s_train, X_s_test, y_s_train, y_s_test = train_test_split(X_std, y_std, test_size=0.15, random_state=42)

In [380]:
model1=LogisticRegression().fit(X_n_train,y_n_train)
model2=LogisticRegression().fit(X_s_train,y_s_train)
print("Standardized Score (train)- ",model2.score(X_s_train,y_s_train))
print("Normalized Score (train) - ",model1.score(X_n_train,y_n_train))
print("Standardized Score (test)- ",model2.score(X_s_test,y_s_test))
print("Normalized Score (test) - ",model1.score(X_n_test,y_n_test))


Standardized Score (train)-  0.813954328660211
Normalized Score (train) -  0.811786385315797
Standardized Score (test)-  0.8122824974411463
Normalized Score (test) -  0.8077789150460594


In [401]:
model1=DecisionTreeClassifier(max_depth=8).fit(X_n_train,y_n_train)
model2=DecisionTreeClassifier(max_depth=8).fit(X_s_train,y_s_train)
print("Standardized Score (train)- ",model2.score(X_s_train,y_s_train))
print("Normalized Score (train) - ",model1.score(X_n_train,y_n_train))
print("Standardized Score (test)- ",model2.score(X_s_test,y_s_test))
print("Normalized Score (test) - ",model1.score(X_n_test,y_n_test))

Standardized Score (train)-  0.8607457725104783
Normalized Score (train) -  0.8607457725104783
Standardized Score (test)-  0.8583418628454452
Normalized Score (test) -  0.8587512794268168


# Dataset 3

In [29]:
df=pd.read_csv("data.csv")
df.drop(columns=["Unnamed: 32",'id'],inplace=True)
df1=pd.DataFrame(df,copy=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [30]:
scaler=StandardScaler()
df.iloc[:,1:]=scaler.fit_transform(df.iloc[:,1:])
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M     1.097064     -2.073335        1.269934   0.984375   
1         M     1.829821     -0.353632        1.685955   1.908708   
2         M     1.579888      0.456187        1.566503   1.558884   
3         M    -0.768909      0.253732       -0.592687  -0.764464   
4         M     1.750297     -1.151816        1.776573   1.826229   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0         1.568466          3.283515        2.652874             2.532475   
1        -0.826962         -0.487072       -0.023846             0.548144   
2         0.942210          1.052926        1.363478             2.037231   
3         3.283553          3.402909        1.915897             1.451707   
4         0.280372          0.539340        1.371011             1.428493   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0       2.217515  ...      1.886690      -1.359293         2.303601   
1       0.001392  ...      1.805927      -0.369203         1.535126   
2       0.939685  ...      1.511870      -0.023974         1.347475   
3       2.867383  ...     -0.281464       0.133984        -0.249939   
4      -0.009560  ...      1.298575      -1.466770         1.338539   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0    2.001237          1.307686           2.616665         2.109526   
1    1.890489         -0.375612          -0.430444        -0.146749   
2    1.456285          0.527407           1.082932         0.854974   
3   -0.550021          3.394275           3.893397         1.989588   
4    1.220724          0.220556          -0.313395         0.613179   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0              2.296076        2.750622                 1.937015  
1              1.087084       -0.243890                 0.281190  
2              1.955000        1.152255                 0.201391  
3              2.175786        6.046041                 4.935010  
4              0.729259       -0.868353                -0.397100  

[5 rows x 31 columns]

In [31]:
scaler1=MinMaxScaler()
df1.iloc[:,1:]=scaler1.fit_transform(df1.iloc[:,1:])
df1.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M     0.521037      0.022658        0.545989   0.363733   
1         M     0.643144      0.272574        0.615783   0.501591   
2         M     0.601496      0.390260        0.595743   0.449417   
3         M     0.210090      0.360839        0.233501   0.102906   
4         M     0.629893      0.156578        0.630986   0.489290   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0         0.593753          0.792037        0.703140             0.731113   
1         0.289880          0.181768        0.203608             0.348757   
2         0.514309          0.431017        0.462512             0.635686   
3         0.811321          0.811361        0.565604             0.522863   
4         0.430351          0.347893        0.463918             0.518390   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0       0.686364  ...      0.620776       0.141525         0.668310   
1       0.379798  ...      0.606901       0.303571         0.539818   
2       0.509596  ...      0.556386       0.360075         0.508442   
3       0.776263  ...      0.248310       0.385928         0.241347   
4       0.378283  ...      0.519744       0.123934         0.506948   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0    0.450698          0.601136           0.619292         0.568610   
1    0.435214          0.347553           0.154563         0.192971   
2    0.374508          0.483590           0.385375         0.359744   
3    0.094008          0.915472           0.814012         0.548642   
4    0.341575          0.437364           0.172415         0.319489   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0              0.912027        0.598462                 0.418864  
1              0.639175        0.233590                 0.222878  
2              0.835052        0.403706                 0.213433  
3              0.884880        1.000000                 0.773711  
4              0.558419        0.157500                 0.142595  

[5 rows x 31 columns]

In [32]:
X_norm=df1.iloc[:,1:]
y_norm=df1["diagnosis"]
X_std=df.iloc[:,1:]
y_std=df["diagnosis"]

In [43]:
X_n_train, X_n_test, y_n_train, y_n_test = train_test_split(X_norm, y_norm, test_size=0.30, random_state=42)
X_s_train, X_s_test, y_s_train, y_s_test = train_test_split(X_std, y_std, test_size=0.30, random_state=42)

In [44]:
model1=LogisticRegression().fit(X_n_train,y_n_train)
model2=LogisticRegression().fit(X_s_train,y_s_train)
print("Standardized Score (train)- ",model2.score(X_s_train,y_s_train))
print("Normalized Score (train) - ",model1.score(X_n_train,y_n_train))
print("Standardized Score (test)- ",model2.score(X_s_test,y_s_test))
print("Normalized Score (test) - ",model1.score(X_n_test,y_n_test))

Standardized Score (train)-  0.9874371859296482
Normalized Score (train) -  0.9673366834170855
Standardized Score (test)-  0.9824561403508771
Normalized Score (test) -  0.9766081871345029


In [45]:
model1=DecisionTreeClassifier().fit(X_n_train,y_n_train)
model2=DecisionTreeClassifier().fit(X_s_train,y_s_train)
print("Standardized Score (train)- ",model2.score(X_s_train,y_s_train))
print("Normalized Score (train) - ",model1.score(X_n_train,y_n_train))
print("Standardized Score (test)- ",model2.score(X_s_test,y_s_test))
print("Normalized Score (test) - ",model1.score(X_n_test,y_n_test))

Standardized Score (train)-  1.0
Normalized Score (train) -  1.0
Standardized Score (test)-  0.9298245614035088
Normalized Score (test) -  0.9298245614035088


# Dataset 4

In [134]:
df=pd.read_csv("StudentsPerformance.csv")
#df.drop(columns=["Unnamed: 32",'id'],inplace=True)
df1=pd.DataFrame(df,copy=True)
df.head()

gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

In [135]:
df["gender"]=df["gender"].apply(lambda x : 1 if x=="male" else 0)
df.head()

gender race/ethnicity parental level of education         lunch  \
0       0        group B           bachelor's degree      standard   
1       0        group C                some college      standard   
2       0        group B             master's degree      standard   
3       1        group A          associate's degree  free/reduced   
4       1        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

In [136]:
ohe=pd.get_dummies(df.iloc[:,1:4])

In [137]:
ohe

race/ethnicity_group A  race/ethnicity_group B  race/ethnicity_group C  \
0                         0                       1                       0   
1                         0                       0                       1   
2                         0                       1                       0   
3                         1                       0                       0   
4                         0                       0                       1   
..                      ...                     ...                     ...   
995                       0                       0                       0   
996                       0                       0                       1   
997                       0                       0                       1   
998                       0                       0                       0   
999                       0                       0                       0   

     race/ethnicity_group D  race/ethnicity_group E  \
0                         0                       0   
1                         0                       0   
2                         0                       0   
3                         0                       0   
4                         0                       0   
..                      ...                     ...   
995                       0                       1   
996                       0                       0   
997                       0                       0   
998                       1                       0   
999                       1                       0   

     parental level of education_associate's degree  \
0                                                 0   
1                                                 0   
2                                                 0   
3                                                 1   
4                                                 0   
..                                              ...   
995                                               0   
996                                               0   
997                                               0   
998                                               0   
999                                               0   

     parental level of education_bachelor's degree  \
0                                                1   
1                                                0   
2                                                0   
3                                                0   
4                                                0   
..                                             ...   
995                                              0   
996                                              0   
997                                              0   
998                                              0   
999                                              0   

     parental level of education_high school  \
0                                          0   
1                                          0   
2                                          0   
3                                          0   
4                                          0   
..                                       ...   
995                                        0   
996                                        1   
997                                        1   
998                                        0   
999                                        0   

     parental level of education_master's degree  \
0                                              0   
1                                              0   
2                                              1   
3                                              0   
4                                              0   
..                                           ...   
995                                            1   
996                                            0   
997                                     

In [138]:
df = pd.concat([df.drop(columns=['race/ethnicity',
                                 'parental level of education','lunch']), ohe], axis=1)

In [139]:
df

gender test preparation course  math score  reading score  writing score  \
0         0                    none          72             72             74   
1         0               completed          69             90             88   
2         0                    none          90             95             93   
3         1                    none          47             57             44   
4         1                    none          76             78             75   
..      ...                     ...         ...            ...            ...   
995       0               completed          88             99             95   
996       1                    none          62             55             55   
997       0               completed          59             71             65   
998       0               completed          68             78             77   
999       0                    none          77             86             86   

     race/ethnicity_group A  race/ethnicity_group B  race/ethnicity_group C  \
0                         0                       1                       0   
1                         0                       0                       1   
2                         0                       1                       0   
3                         1                       0                       0   
4                         0                       0                       1   
..                      ...                     ...                     ...   
995                       0                       0                       0   
996                       0                       0                       1   
997                       0                       0                       1   
998                       0                       0                       0   
999                       0                       0                       0   

     race/ethnicity_group D  race/ethnicity_group E  \
0                         0                       0   
1                         0                       0   
2                         0                       0   
3                         0                       0   
4                         0                       0   
..                      ...                     ...   
995                       0                       1   
996                       0                       0   
997                       0                       0   
998                       1                       0   
999                       1                       0   

     parental level of education_associate's degree  \
0                                                 0   
1                                                 0   
2                                                 0   
3                                                 1   
4                                                 0   
..                                              ...   
995                                               0   
996                                               0   
997                                               0   
998                                               0   
999                                               0   

     parental level of education_bachelor's degree  \
0                                                1   
1                                                0   
2                                                0   
3                                                0   
4                                                0   
..                                             ...   
995                                              0   
996                                              0   
997                                              0   
998                                              0   
999                                              0   

     parental level of education_high school  \
0                                          0   
1               

In [140]:
df["test preparation course"]=df["test preparation course"].apply(lambda x : 1 if x=="completed" else 0)

In [141]:
df

gender  test preparation course  math score  reading score  \
0         0                        0          72             72   
1         0                        1          69             90   
2         0                        0          90             95   
3         1                        0          47             57   
4         1                        0          76             78   
..      ...                      ...         ...            ...   
995       0                        1          88             99   
996       1                        0          62             55   
997       0                        1          59             71   
998       0                        1          68             78   
999       0                        0          77             86   

     writing score  race/ethnicity_group A  race/ethnicity_group B  \
0               74                       0                       1   
1               88                       0                       0   
2               93                       0                       1   
3               44                       1                       0   
4               75                       0                       0   
..             ...                     ...                     ...   
995             95                       0                       0   
996             55                       0                       0   
997             65                       0                       0   
998             77                       0                       0   
999             86                       0                       0   

     race/ethnicity_group C  race/ethnicity_group D  race/ethnicity_group E  \
0                         0                       0                       0   
1                         1                       0                       0   
2                         0                       0                       0   
3                         0                       0                       0   
4                         1                       0                       0   
..                      ...                     ...                     ...   
995                       0                       0                       1   
996                       1                       0                       0   
997                       1                       0                       0   
998                       0                       1                       0   
999                       0                       1                       0   

     parental level of education_associate's degree  \
0                                                 0   
1                                                 0   
2                                                 0   
3                                                 1   
4                                                 0   
..                                              ...   
995                                               0   
996                                               0   
997                                               0   
998                                               0   
999                                               0   

     parental level of education_bachelor's degree  \
0                                                1   
1                                                0   
2                                                0   
3                                                0   
4                                                0   
..                                             ...   
995                                              0   
996                                              0   
997                                              0   
998                                              0   
999                                              0   

     parental level of education_high school  \
0                                          0   
1   

In [142]:
df1=pd.DataFrame(df,copy=True)

In [143]:
scaler=StandardScaler()
df.iloc[:,2:5]=scaler.fit_transform(df.iloc[:,2:5])
df.head()

gender  test preparation course  math score  reading score  writing score  \
0       0                        0    0.390024       0.193999       0.391492   
1       0                        1    0.192076       1.427476       1.313269   
2       0                        0    1.577711       1.770109       1.642475   
3       1                        0   -1.259543      -0.833899      -1.583744   
4       1                        0    0.653954       0.605158       0.457333   

   race/ethnicity_group A  race/ethnicity_group B  race/ethnicity_group C  \
0                       0                       1                       0   
1                       0                       0                       1   
2                       0                       1                       0   
3                       1                       0                       0   
4                       0                       0                       1   

   race/ethnicity_group D  race/ethnicity_group E  \
0                       0                       0   
1                       0                       0   
2                       0                       0   
3                       0                       0   
4                       0                       0   

   parental level of education_associate's degree  \
0                                               0   
1                                               0   
2                                               0   
3                                               1   
4                                               0   

   parental level of education_bachelor's degree  \
0                                              1   
1                                              0   
2                                              0   
3                                              0   
4                                              0   

   parental level of education_high school  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   

   parental level of education_master's degree  \
0                                            0   
1                                            0   
2                                            1   
3                                            0   
4                                            0   

   parental level of education_some college  \
0                                         0   
1                                         1   
2                                         0   
3                                         0   
4                                         1   

   parental level of education_some high school  lunch_free/reduced  \
0                                             0                   0   
1                                             0                   0   
2                                             0                   0   
3                                             0                   1   
4                                             0                   0   

   lunch_standard  
0               1  
1               1  
2               1  
3               0  
4               1

In [144]:
scaler1=MinMaxScaler()
df1.iloc[:,2:5]=scaler1.fit_transform(df1.iloc[:,2:5])
df1.head()

gender  test preparation course  math score  reading score  writing score  \
0       0                        0        0.72       0.662651       0.711111   
1       0                        1        0.69       0.879518       0.866667   
2       0                        0        0.90       0.939759       0.922222   
3       1                        0        0.47       0.481928       0.377778   
4       1                        0        0.76       0.734940       0.722222   

   race/ethnicity_group A  race/ethnicity_group B  race/ethnicity_group C  \
0                       0                       1                       0   
1                       0                       0                       1   
2                       0                       1                       0   
3                       1                       0                       0   
4                       0                       0                       1   

   race/ethnicity_group D  race/ethnicity_group E  \
0                       0                       0   
1                       0                       0   
2                       0                       0   
3                       0                       0   
4                       0                       0   

   parental level of education_associate's degree  \
0                                               0   
1                                               0   
2                                               0   
3                                               1   
4                                               0   

   parental level of education_bachelor's degree  \
0                                              1   
1                                              0   
2                                              0   
3                                              0   
4                                              0   

   parental level of education_high school  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   

   parental level of education_master's degree  \
0                                            0   
1                                            0   
2                                            1   
3                                            0   
4                                            0   

   parental level of education_some college  \
0                                         0   
1                                         1   
2                                         0   
3                                         0   
4                                         1   

   parental level of education_some high school  lunch_free/reduced  \
0                                             0                   0   
1                                             0                   0   
2                                             0                   0   
3                                             0                   1   
4                                             0                   0   

   lunch_standard  
0               1  
1               1  
2               1  
3               0  
4               1

In [145]:
X_norm=df1.iloc[:,2:]
X_norm.insert(0,"gender",df1["gender"])
y_norm=df1["test preparation course"]
X_std=df.iloc[:,2:]
X_std.insert(0,"gender",df["gender"])
y_std=df["test preparation course"]

In [186]:
X_n_train, X_n_test, y_n_train, y_n_test = train_test_split(X_norm, y_norm, test_size=0.4)
X_s_train, X_s_test, y_s_train, y_s_test = train_test_split(X_std, y_std, test_size=0.4)

In [187]:
model1=LogisticRegression().fit(X_n_train,y_n_train)
model2=LogisticRegression().fit(X_s_train,y_s_train)
print("Standardized Score (train)- ",model2.score(X_s_train,y_s_train))
print("Normalized Score (train) - ",model1.score(X_n_train,y_n_train))
print("Standardized Score (test)- ",model2.score(X_s_test,y_s_test))
print("Normalized Score (test) - ",model1.score(X_n_test,y_n_test))

Standardized Score (train)-  0.76
Normalized Score (train) -  0.6866666666666666
Standardized Score (test)-  0.72
Normalized Score (test) -  0.705


In [188]:
model1=DecisionTreeClassifier().fit(X_n_train,y_n_train)
model2=DecisionTreeClassifier().fit(X_s_train,y_s_train)
print("Standardized Score (train)- ",model2.score(X_s_train,y_s_train))
print("Normalized Score (train) - ",model1.score(X_n_train,y_n_train))
print("Standardized Score (test)- ",model2.score(X_s_test,y_s_test))
print("Normalized Score (test) - ",model1.score(X_n_test,y_n_test))

Standardized Score (train)-  1.0
Normalized Score (train) -  1.0
Standardized Score (test)-  0.6325
Normalized Score (test) -  0.6325


# Dataset 5

In [132]:
df=pd.read_csv("mushrooms.csv")
df.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

In [133]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [134]:
for i in df.columns:
    df[i]=le.fit_transform(df[i])
df.head()

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [57]:
for i in df.columns:
    print(df[i].unique())

[1 0]
[5 0 4 2 3 1]
[2 3 0 1]
[4 9 8 3 2 5 0 7 1 6]
[1 0]
[6 0 3 5 2 1 8 7 4]
[1 0]
[0 1]
[1 0]
[ 4  5  2  7 10  3  9  1  0  8 11  6]
[0 1]
[3 2 1 4 0]
[2 0 1 3]
[2 0 3 1]
[7 3 6 4 0 2 5 1 8]
[7 6 3 0 4 2 8 5 1]
[0]
[2 0 1 3]
[1 2 0]
[4 0 2 1 3]
[2 3 6 1 7 5 4 8 0]
[3 2 0 4 5 1]
[5 1 3 0 4 6 2]


In [66]:
from sklearn import preprocessing
df.iloc[:,1:]=preprocessing.scale(df.iloc[:,1:])
df.head()

class  cap-shape  cap-surface  cap-color   bruises      odor  \
0      1   1.029712     0.140128  -0.198250  1.185917  0.881938   
1      0   1.029712     0.140128   1.765874  1.185917 -1.970316   
2      0  -2.087047     0.140128   1.373049  1.185917 -0.544189   
3      1   1.029712     0.953270   1.373049  1.185917  0.881938   
4      0   1.029712     0.140128  -0.591075 -0.843230  0.406562   

   gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0         0.162896     -0.438864   1.494683   -0.228998  ...   
1         0.162896     -0.438864  -0.669038   -0.228998  ...   
2         0.162896     -0.438864  -0.669038    0.053477  ...   
3         0.162896     -0.438864   1.494683    0.053477  ...   
4         0.162896      2.278612  -0.669038   -0.228998  ...   

   stalk-surface-below-ring  stalk-color-above-ring  stalk-color-below-ring  \
0                  0.586385                0.622441                0.631991   
1                  0.586385                0.622441                0.631991   
2                  0.586385                0.622441                0.631991   
3                  0.586385                0.622441                0.631991   
4                  0.586385                0.622441                0.631991   

   veil-type  veil-color  ring-number  ring-type  spore-print-color  \
0        0.0    0.142037    -0.256132   0.948081          -0.670195   
1        0.0    0.142037    -0.256132   0.948081          -0.250471   
2        0.0    0.142037    -0.256132   0.948081          -0.250471   
3        0.0    0.142037    -0.256132   0.948081          -0.670195   
4        0.0    0.142037    -0.256132  -1.272216          -0.250471   

   population   habitat  
0   -0.514389  2.030028  
1   -1.313108 -0.295730  
2   -1.313108  0.867149  
3   -0.514389  2.030028  
4   -2.910546 -0.295730  

[5 rows x 23 columns]

In [59]:
X=df.drop(columns=['class'])
y=df['class']

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [64]:
model=LogisticRegression().fit(X_train,y_train)
print("Score (train)- ",model.score(X_train,y_train))
print("Score (test) - ",model.score(X_test,y_test))

Score (train)-  0.9572241883366672
Score (test) -  0.952


In [65]:
model1=DecisionTreeClassifier().fit(X_train,y_train)
model2=DecisionTreeClassifier().fit(X_train,y_train)
print("Score (train)- ",model.score(X_train,y_train))
print("Score (test) - ",model.score(X_test,y_test))

Score (train)-  0.9572241883366672
Score (test) -  0.952


# Mushroom Final Dataset Operations

In [225]:
df=pd.read_csv("mushrooms_finalized.csv")
df.drop(columns="Unnamed: 0",inplace=True)
df.head()

class cap-shape cap-surface cap-color odor gill-attachment gill-spacing  \
0     p         x           s         n    p               f            c   
1     e         x           s         y    a               f            c   
2     e         b           s         w    l               f            c   
3     p         x           y         w    p               f            c   
4     e         x           s         g    n               f            w   

  gill-color stalk-shape stalk-root stalk-surface-above-ring  \
0          k           e          e                        s   
1          k           e          c                        s   
2          n           e          c                        s   
3          n           e          e                        s   
4          k           t          e                        s   

  stalk-surface-below-ring stalk-color-below-ring veil-type veil-color  \
0                        s                      w         p          w   
1                        s                      w         p          w   
2                        s                      w         p          w   
3                        s                      w         p          w   
4                        s                      w         p          w   

  ring-number ring-type spore-print-color population  
0           o         p                 k          s  
1           o         p                 n          n  
2           o         p                 n          n  
3           o         p                 k          s  
4           o         e                 n          a

In [226]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['class']=le.fit_transform(df['class'])
c=pd.get_dummies(df.iloc[:,1:])
df=df['class']
df=pd.concat([df,c],axis=1)
df

class  cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  \
0         1            0            0            0            0            0   
1         0            0            0            0            0            0   
2         0            1            0            0            0            0   
3         1            0            0            0            0            0   
4         0            0            0            0            0            0   
...     ...          ...          ...          ...          ...          ...   
8119      0            0            0            0            1            0   
8120      0            0            0            0            0            0   
8121      0            0            0            1            0            0   
8122      1            0            0            0            1            0   
8123      0            0            0            0            0            0   

      cap-shape_x  cap-surface_f  cap-surface_g  cap-surface_s  ...  \
0               1              0              0              1  ...   
1               1              0              0              1  ...   
2               0              0              0              1  ...   
3               1              0              0              0  ...   
4               1              0              0              1  ...   
...           ...            ...            ...            ...  ...   
8119            0              0              0              1  ...   
8120            1              0              0              1  ...   
8121            0              0              0              1  ...   
8122            0              0              0              0  ...   
8123            1              0              0              1  ...   

      spore-print-color_r  spore-print-color_u  spore-print-color_w  \
0                       0                    0                    0   
1                       0                    0                    0   
2                       0                    0                    0   
3                       0                    0                    0   
4                       0                    0                    0   
...                   ...                  ...                  ...   
8119                    0                    0                    0   
8120                    0                    0                    0   
8121                    0                    0                    0   
8122                    0                    0                    1   
8123                    0                    0                    0   

      spore-print-color_y  population_a  population_c  population_n  \
0                       0             0             0             0   
1                       0             0             0             1   
2                       0             0             0             1   
3                       0             0             0             0   
4                       0             1             0             0   
...                   ...           ...           ...           ...   
8119                    0             0             1             0   
8120                    0             0             0             0   
8121                    0             0             1             0   
8122                    0             0             0             0   
8123                    0             0             1             0   

      population_s  population_v  population_y  
0                1             0             0  
1                0             0             0  
2                0             0             0  
3                1             0             0  
4                0             0             0  
...            ...           ...           ...  
8119             0             0             0  
8120             0             1             0  
8121             0             0             

In [223]:
df.head()

class  cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  \
0      1            0            0            0            0            0   
1      0            0            0            0            0            0   
2      0            1            0            0            0            0   
3      1            0            0            0            0            0   
4      0            0            0            0            0            0   

   cap-shape_x  cap-surface_f  cap-surface_g  cap-surface_s  ...  \
0            1              0              0              1  ...   
1            1              0              0              1  ...   
2            0              0              0              1  ...   
3            1              0              0              0  ...   
4            1              0              0              1  ...   

   spore-print-color_r  spore-print-color_u  spore-print-color_w  \
0                    0                    0                    0   
1                    0                    0                    0   
2                    0                    0                    0   
3                    0                    0                    0   
4                    0                    0                    0   

   spore-print-color_y  population_a  population_c  population_n  \
0                    0             0             0             0   
1                    0             0             0             1   
2                    0             0             0             1   
3                    0             0             0             0   
4                    0             1             0             0   

   population_s  population_v  population_y  
0             1             0             0  
1             0             0             0  
2             0             0             0  
3             1             0             0  
4             0             0             0  

[5 rows x 98 columns]

In [224]:
from sklearn import preprocessing
scaler=MinMaxScaler()
df.iloc[:,1:]=scaler.fit_transform(df.iloc[:,1:])
df.head()

class  cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  \
0      1          0.0          0.0          0.0          0.0          0.0   
1      0          0.0          0.0          0.0          0.0          0.0   
2      0          1.0          0.0          0.0          0.0          0.0   
3      1          0.0          0.0          0.0          0.0          0.0   
4      0          0.0          0.0          0.0          0.0          0.0   

   cap-shape_x  cap-surface_f  cap-surface_g  cap-surface_s  ...  \
0          1.0            0.0            0.0            1.0  ...   
1          1.0            0.0            0.0            1.0  ...   
2          0.0            0.0            0.0            1.0  ...   
3          1.0            0.0            0.0            0.0  ...   
4          1.0            0.0            0.0            1.0  ...   

   spore-print-color_r  spore-print-color_u  spore-print-color_w  \
0                  0.0                  0.0                  0.0   
1                  0.0                  0.0                  0.0   
2                  0.0                  0.0                  0.0   
3                  0.0                  0.0                  0.0   
4                  0.0                  0.0                  0.0   

   spore-print-color_y  population_a  population_c  population_n  \
0                  0.0           0.0           0.0           0.0   
1                  0.0           0.0           0.0           1.0   
2                  0.0           0.0           0.0           1.0   
3                  0.0           0.0           0.0           0.0   
4                  0.0           1.0           0.0           0.0   

   population_s  population_v  population_y  
0           1.0           0.0           0.0  
1           0.0           0.0           0.0  
2           0.0           0.0           0.0  
3           1.0           0.0           0.0  
4           0.0           0.0           0.0  

[5 rows x 98 columns]

In [227]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 98 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   class                       8124 non-null   int32
 1   cap-shape_b                 8124 non-null   uint8
 2   cap-shape_c                 8124 non-null   uint8
 3   cap-shape_f                 8124 non-null   uint8
 4   cap-shape_k                 8124 non-null   uint8
 5   cap-shape_s                 8124 non-null   uint8
 6   cap-shape_x                 8124 non-null   uint8
 7   cap-surface_f               8124 non-null   uint8
 8   cap-surface_g               8124 non-null   uint8
 9   cap-surface_s               8124 non-null   uint8
 10  cap-surface_y               8124 non-null   uint8
 11  cap-color_b                 8124 non-null   uint8
 12  cap-color_c                 8124 non-null   uint8
 13  cap-color_e                 8124 non-null   uint8
 14  cap-colo

In [228]:
X=df.drop(columns=['class'])
y=df['class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=42)
model=LogisticRegression().fit(X_train,y_train)
print(model.score(X_test,y_test))
print(model.score(X_train,y_train))

0.9995898277276456
0.9996482588814632


In [172]:
X=df.drop(columns=['class','bruises','gill-size','stalk-color-above-ring','habitat'])
y=df['class']

In [210]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=42)

In [211]:
from sklearn.metrics import accuracy_score
model=LogisticRegression().fit(X_train,y_train)
print("Score (train)- ",accuracy_score(y_train,model.predict(X_train)))
print("Score (test) - ",accuracy_score(y_test,model.predict(X_test)))

Score (train)-  1.0
Score (test) -  1.0


In [212]:
model=DecisionTreeClassifier().fit(X_train,y_train)
print("Score (train)- ",accuracy_score(y_train,model.predict(X_train)))
print("Score (test) - ",accuracy_score(y_test,model.predict(X_test)))

Score (train)-  1.0
Score (test) -  1.0


In [182]:
df2=df.drop(columns=['bruises','gill-size','stalk-color-above-ring','habitat'])
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   odor                      8124 non-null   object
 5   gill-attachment           8124 non-null   object
 6   gill-spacing              8124 non-null   object
 7   gill-color                8124 non-null   object
 8   stalk-shape               8124 non-null   object
 9   stalk-root                8124 non-null   object
 10  stalk-surface-above-ring  8124 non-null   object
 11  stalk-surface-below-ring  8124 non-null   object
 12  stalk-color-below-ring    8124 non-null   object
 13  veil-type                 8124 non-null   object
 14  veil-color              

In [183]:
df2.to_csv("mushrooms_finalized.csv")

In [184]:
pd.read_csv("mushrooms_finalized.csv")

Unnamed: 0 class cap-shape cap-surface cap-color odor gill-attachment  \
0              0     p         x           s         n    p               f   
1              1     e         x           s         y    a               f   
2              2     e         b           s         w    l               f   
3              3     p         x           y         w    p               f   
4              4     e         x           s         g    n               f   
...          ...   ...       ...         ...       ...  ...             ...   
8119        8119     e         k           s         n    n               a   
8120        8120     e         x           s         n    n               a   
8121        8121     e         f           s         n    n               a   
8122        8122     p         k           y         n    y               f   
8123        8123     e         x           s         n    n               a   

     gill-spacing gill-color stalk-shape stalk-root stalk-surface-above-ring  \
0               c          k           e          e                        s   
1               c          k           e          c                        s   
2               c          n           e          c                        s   
3               c          n           e          e                        s   
4               w          k           t          e                        s   
...           ...        ...         ...        ...                      ...   
8119            c          y           e          ?                        s   
8120            c          y           e          ?                        s   
8121            c          n           e          ?                        s   
8122            c          b           t          ?                        s   
8123            c          y           e          ?                        s   

     stalk-surface-below-ring stalk-color-below-ring veil-type veil-color  \
0                           s                      w         p          w   
1                           s                      w         p          w   
2                           s                      w         p          w   
3                           s                      w         p          w   
4                           s                      w         p          w   
...                       ...                    ...       ...        ...   
8119                        s                      o         p          o   
8120                        s                      o         p          n   
8121                        s                      o         p          o   
8122                        k                      w         p          w   
8123                        s                      o         p          o   

     ring-number ring-type spore-print-color population  
0              o         p                 k          s  
1              o         p                 n          n  
2              o         p                 n          n  
3              o         p                 k          s  
4              o         e                 n          a  
...          ...       ...               ...        ...  
8119           o         p                 b          c  
8120           o         p                 b          v  
8121           o         p                 b          c  
8122           o         e                 w          v  
8123           o         p                 o          c  

[8124 rows x 20 columns]