## Logistic Regression Modeling for Early Stage Diabetes Risk Prediction

## Part 2.1: Getting familiar with linear algebraic functions

#### Tasks
- Create matrix of size 10*10 with random integer numbers
- Compute the following linear algebric operations on the matrix using built in functions supported in Numpy, Scipy etc.
  - Find inverse of the matrix and print it
  - Calculate dot product of the matrix with same matrix in transpose A.AT
  - Decompose the original matrix using eigen decomposition print the eigen values and eigen vectors
  - Calculate jacobian matrix 
  - Calculate hessian matrix

In [30]:
import numpy as np
a=np.random.rand(10,10)
b=np.random.rand(10,10)

In [31]:
inva=np.linalg.inv(a)
inva

array([[ 0.1317605 ,  0.14193943,  0.79549129, -1.67110839,  1.37963929,
         0.22097196,  0.72410053, -0.13814585,  0.74768078, -2.01466235],
       [-2.6095634 ,  1.08910692,  2.86399697, -1.69186905,  1.69437172,
        -4.61221837, -0.08942897, -3.99738266,  5.5372264 ,  0.78206469],
       [ 3.48647724, -0.98778431, -6.35195669,  3.72197042, -4.18540161,
         7.92128811,  0.10916805,  6.52829342, -7.84885674, -0.24408697],
       [ 0.25102139,  2.04742623,  0.22017065,  1.36310247, -0.42339381,
        -2.85806564,  0.44590008, -1.49618119, -0.20510395,  0.72387142],
       [-3.14375527, -0.36683319,  6.60714678, -3.5116636 ,  3.84495432,
        -4.73589027,  0.01917466, -5.87619518,  6.17748668, -0.31237318],
       [ 1.367251  ,  1.25181009, -1.02511043,  0.21253863, -1.21424674,
        -0.74727493,  0.32493035,  0.91019968, -1.10749776,  0.30424712],
       [ 0.39522702,  0.25192275, -0.73667275,  1.43858252, -0.77685174,
         0.06631761,  1.25882701,  0.94746038

In [32]:
np.dot(a,a.T)

array([[3.92268526, 2.21468371, 2.64379837, 2.50813295, 3.2027654 ,
        2.54967053, 3.03416561, 2.44906083, 3.28739581, 3.61874842],
       [2.21468371, 2.79522789, 2.54352739, 1.92083574, 2.14350538,
        2.65231823, 2.52186469, 2.09470954, 2.58539002, 3.05679698],
       [2.64379837, 2.54352739, 3.33617091, 2.24510413, 1.75064068,
        2.50535896, 2.59602626, 2.81707382, 2.99802442, 3.10552769],
       [2.50813295, 1.92083574, 2.24510413, 2.50849883, 2.36749776,
        2.00806981, 2.29260818, 2.19606074, 2.73401356, 2.42974147],
       [3.2027654 , 2.14350538, 1.75064068, 2.36749776, 3.86356988,
        2.39351843, 3.10124717, 2.01407041, 2.78144278, 3.55019953],
       [2.54967053, 2.65231823, 2.50535896, 2.00806981, 2.39351843,
        2.78166386, 2.7427704 , 2.0150441 , 2.7432954 , 3.2665699 ],
       [3.03416561, 2.52186469, 2.59602626, 2.29260818, 3.10124717,
        2.7427704 , 3.56793614, 2.77294015, 3.28810705, 3.84751469],
       [2.44906083, 2.09470954, 2.8170738

In [33]:
w,v=np.linalg.eig(a)
w,v

(array([ 5.19594821+0.j        , -0.60319215+0.19447981j,
        -0.60319215-0.19447981j,  0.34452296+0.69284833j,
         0.34452296-0.69284833j, -0.22348589+0.j        ,
         0.32086014+0.24538349j,  0.32086014-0.24538349j,
         0.08657808+0.16143308j,  0.08657808-0.16143308j]),
 array([[-0.35072544+0.j        ,  0.06814155-0.046351j  ,
          0.06814155+0.046351j  ,  0.42187871-0.10514727j,
          0.42187871+0.10514727j, -0.11144587+0.j        ,
         -0.27103656+0.13348167j, -0.27103656-0.13348167j,
         -0.09213904-0.01839121j, -0.09213904+0.01839121j],
        [-0.26212671+0.j        ,  0.04880203-0.08720794j,
          0.04880203+0.08720794j, -0.31398256-0.26116426j,
         -0.31398256+0.26116426j,  0.33772409+0.j        ,
         -0.18526849-0.32899665j, -0.18526849+0.32899665j,
         -0.39012128-0.11332632j, -0.39012128+0.11332632j],
        [-0.29091249+0.j        , -0.54378877+0.j        ,
         -0.54378877-0.j        , -0.13168664-0.10931071j

In [34]:
import numdifftools as nd

## Part 2.2: Logistic Regression using newton method

### Logistic regression
Logistic regression uses an equation as the representation, very much like linear regression.

Input values (x) are combined linearly using weights or coefficient values (referred to as W) to predict an output value (y). A key difference from linear regression is that the output value being modeled is a binary values (0 or 1) rather than a continuous value.<br>

###  $\hat{y}(w, x) = \frac{1}{1+exp^{-(w_0 + w_1 * x_1 + ... + w_p * x_p)}}$

#### Dataset
The dataset is available at <strong>"data/diabetes_data.csv"</strong> in the respective challenge's repo.<br>
<strong>Original Source:</strong> http://archive.ics.uci.edu/ml/machine-learning-databases/00529/diabetes_data_upload.csv. The dataset just got released in July 2020.<br><br>

#### Features (X)

1. Age                - Values ranging from 16-90
2. Gender             - Binary value (Male/Female)
3. Polyuria           - Binary value (Yes/No)
4. Polydipsia         - Binary value (Yes/No)
5. sudden weight loss - Binary value (Yes/No)
6. weakness           - Binary value (Yes/No)
7. Polyphagia         - Binary value (Yes/No)
8. Genital thrush     - Binary value (Yes/No)
9. visual blurring    - Binary value (Yes/No)
10. Itching           - Binary value (Yes/No)
11. Irritability      - Binary value (Yes/No)
12. delayed healing   - Binary value (Yes/No)
13. partial paresis   - Binary value (Yes/No)
14. muscle stiffness  - Binary value (Yes/No)
15. Alopecia          - Binary value (Yes/No)
16. Obesity           - Binary value (Yes/No)

#### Output/Target target (Y) 
17. class - Binary class (Positive/Negative)

#### Objective
To learn logistic regression and practice handling of both numerical and categorical features

#### Tasks
- Download, load the data and print first 5 and last 5 rows
- Transform categorical features into numerical features. Use label encoding or any other suitable preprocessing technique
- Since the age feature is in larger range, age column can be normalized into smaller scale (like 0 to 1) using different methods such as scaling, standardizing or any other suitable preprocessing technique (Example - sklearn.preprocessing.MinMaxScaler class)
- Define X matrix (independent features) and y vector (target feature)
- Split the dataset into 60% for training and rest 40% for testing (sklearn.model_selection.train_test_split function)
- Train Logistic Regression Model on the training set (sklearn.linear_model.LogisticRegression class)
- Use the trained model to predict on testing set
- Print 'Accuracy' obtained on the testing dataset i.e. (sklearn.metrics.accuracy_score function)

#### Further fun (will not be evaluated)
- Plot loss curve (Loss vs number of iterations)
- Preprocess data with different feature scaling methods (i.e. scaling, normalization, standardization, etc) and observe accuracies on both X_train and X_test
- Training model on different train-test splits such as 60-40, 50-50, 70-30, 80-20, 90-10, 95-5 etc. and observe accuracies on both X_train and X_test
- Shuffling of training samples with different *random seed values* in the train_test_split function. Check the model error for the testing data for each setup.
- Print other classification metrics such as:
    - classification report (sklearn.metrics.classification_report),
    - confusion matrix (sklearn.metrics.confusion_matrix),
    - precision, recall and f1 scores (sklearn.metrics.precision_recall_fscore_support)

#### Helpful links
- Scikit-learn documentation for logistic regression: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
- How Logistic Regression works: https://machinelearningmastery.com/logistic-regression-for-machine-learning/
- Feature Scaling: https://scikit-learn.org/stable/modules/preprocessing.html
- Training testing splitting: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
- Classification metrics in sklearn: https://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics
- Use slack for doubts: https://join.slack.com/t/deepconnectai/shared_invite/zt-givlfnf6-~cn3SQ43k0BGDrG9_YOn4g

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


In [ ]:
# Download the dataset from the source
!wget _URL_

In [ ]:
# NOTE: DO NOT CHANGE THE VARIABLE NAME(S) IN THIS CELL
# Load the data
data = 

In [ ]:
# Handle categorical/binary columns

In [ ]:
# Normalize the age feature

In [ ]:
# Define your X and y
X = 
y = 

In [ ]:
# Split the dataset into training and testing here
X_train, X_test, y_train, y_test = 

In [ ]:
def predict(X, weights):
    '''Predict class for X.
    For the given dataset, predicted vector has only values 0/1
    Args:
        X : Numpy array (num_samples, num_features)
        weights : Model weights for logistic regression
    Returns:
        Binary predictions : (num_samples,)
    '''

    ### START CODE HERE ###
    z = 
    logits = 
    y_pred = 
    ### END CODE HERE ###
    
    return y_pred

In [ ]:
def sigmoid(z):
        '''Sigmoid function: f:R->(0,1)
        Args:
            z : A numpy array (num_samples,)
        Returns:
            A numpy array where sigmoid function applied to every element
        '''
        ### START CODE HERE
        sig_z = 
        ### END CODE HERE
        
        assert (z.shape==sig_z.shape), 'Error in sigmoid implementation. Check carefully'
        return sig_z

In [ ]:
def cross_entropy_loss(y_true, y_pred):
    '''Calculate cross entropy loss
    Note: Cross entropy is defined for multiple classes/labels as well
    but for this dataset we only need binary cross entropy loss
    Args:
        y_true : Numpy array of true values (0/1) of size (num_samples,)
        y_pred : Numpy array of predicted values (probabilites) of size (num_samples,)
    Returns:
        Cross entropy loss: A scalar value
    '''
    # Fix 0 values in y_pred
    y_pred = np.maximum(np.full(y_pred.shape, 1e-7), np.minimum(np.full(y_pred.shape, 1-1e-7), y_pred))
    
    ### START CODE HERE
    ce_loss = 
    ### END CODE HERE
    
    return ce_loss

In [ ]:
def newton_optimization(X, y, max_iterations=25):
    '''Implement netwon method for optimizing weights
    Args:
        X : Numpy array (num_samples, num_features)
        max_iterations : Max iterations to update the weights
    Returns:
        Optimal weights (num_features,)
    '''
    num_samples = X.shape[0]
    num_features = X.shape[1]
    # Initialize random weights
    weights = np.zeros(num_features,)
    # Initialize losses
    losses = []
    
    # Newton Method
    for i in range(max_iterations):
        # Predict/Calculate probabilties using sigmoid function
        y_p = 
        
        # Define gradient for J (cost function) i.e. cross entropy loss
        gradient = 
        
        # Define hessian matrix for cross entropy loss
        hessian =
        
        # Update the model using hessian matrix and gradient computed
        weights = 
        
        # Calculate cross entropy loss
        loss = cross_entropy_loss(y, y_p)
        # Append it
        losses.append(loss)

    return weights, losses

In [ ]:
# Train weights
weights, losses = newton_optimization(X_train, y_train)

In [ ]:
# Plot the loss curve
plt.plot([i+1 for i in range(len(losses))], losses)
plt.title("Loss curve")
plt.xlabel("Iteration num")
plt.ylabel("Cross entropy curve")
plt.show()

In [ ]:
our_model_test_acuracy = accuracy_score(y_test, predict(X_test, weights))

print(f"\nAccuracy in testing set by our model: {our_model_test_acuracy}")

#### Compare with the scikit learn implementation

In [ ]:
# Initialize the model
model = LogisticRegression(solver='newton-cg', verbose=1)

In [ ]:
# Fit the model. Wait! We will complete this step for you ;)
model.fit(X_train, y_train)

In [ ]:
# Predict on testing set X_test
y_pred = model.predict(X_test)

In [ ]:
# Print Accuracy on testing set
sklearn_test_accuracy = accuracy_score(y_test, y_pred)

print(f"\nAccuracy in testing set by sklearn model: {sklearn_test_accuracy}")